### ISSUE TITLE
Specify if use a extra space

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/pretty-bytes#11]
What's do you think about this:

```
prettyBytes(1337);
//=> '1.34 kB'
```

```
prettyBytes(1337, { space: false });
//=> '1.34kB'
```

**Comment by kevva** [comment]
Why?

**Comment by Kikobeats** [comment]
just esthetic

**Comment by sindresorhus** [comment]
No thanks. I'm not interested in adding useless options like that. The default is the correct notation and what you should use. If you want something different you can easily just do `prettyBytes(1337).replace(' ', '');`.
