### ISSUE TITLE
Add to jsDelivr

### ISSUE THREAD

**Issue by DiegoRBaquero** [sindresorhus/pretty-bytes#14]
Hey,

I wanted to suggest that you add this awesome package to https://www.jsdelivr.com/

Cheers

**Comment by sindresorhus** [comment]
Feel free to add it if you want it there. I personally only care about it being on npm.

**Comment by styfle** [comment]
@DiegoRBaquero It is available on jsdelivr now:

https://cdn.jsdelivr.net/npm/pretty-bytes@4.0.2/index.js
