### ISSUE TITLE
Why kB instead of KB?

### ISSUE THREAD

**Issue by feross** [sindresorhus/pretty-bytes#17]
It's the only size that starts with a lowercase letter. What's the reason?

**Comment by silverwind** [comment]
These are [SI prefixes](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes).

**Comment by fanatid** [comment]
Related PR: https://github.com/sindresorhus/pretty-bytes/pull/5

**Comment by sindresorhus** [comment]
Yup, from the readme:

> *Note that it uses base-10 (eg. kilobyte).  
[Read about the difference between kilobyte and kibibyte.](http://pacoup.com/2009/05/26/kb-kb-kib-whats-up-with-that/)*

Suggestions welcome on how this can be better clarified :)

**Comment by feross** [comment]
Fair enough :) If the goal is accuracy, then `kB` is correct. I'd argue that going for prettiness in this case makes more sense. For example, OS X switched from 1024 to 1000 in Snow Leopard but kept the `KB` labeling since users don't care and it looks consistent:

<img width="710" alt="screen shot 2016-03-08 at 1 01 50 pm" src="https://cloud.githubusercontent.com/assets/121766/13616298/295e623e-e52e-11e5-9262-99f2cbf1f7e5.png">

Feel free to close this issue if you disagree. :)

**Comment by sindresorhus** [comment]
> If the goal is accuracy

Always ;)

**Comment by silverwind** [comment]
> OS X switched from 1024 to 1000 in Snow Leopard but kept the KB 

Mixing SI units with JEDEC prefixes is just horrible. Even Windows does it better and uses base-1024 with JEDEC prefixes.
