### ISSUE TITLE
precomputed values

### ISSUE THREAD

**Issue by fanatid** [sindresorhus/pretty-bytes#18]
Why not use precomputed values?
- `Math.log(1000)` -- https://github.com/sindresorhus/pretty-bytes/blob/7880c0805ea4647455a95ee899d0da1b5f175e0f/index.js#L22
- `Math.pow(1000, exponent)` -- https://github.com/sindresorhus/pretty-bytes/blob/7880c0805ea4647455a95ee899d0da1b5f175e0f/index.js#L23

**Comment by sindresorhus** [comment]
What's the point? It's clearer like it is now and precomputing for the sake of performance would be a pretty big [premature optimization](http://c2.com/cgi/wiki?PrematureOptimization).
