### ISSUE TITLE
Use Number.toPrecision(3) instead of Number.toFixed(2)

### ISSUE THREAD

**Issue by deadbeef84** [sindresorhus/pretty-bytes#19]
I'm suggesting switching to Number.toPrecision(3) instead of Number.toFixed(2).

value | toFixed(2) | toPrecision(3)
--------|---------------|--------------------
123.4 | 123.40 | 123
12.34 | 12.34 | 12.3
1.234 | 1.23 | 1.23
123 | 123.00 | 123
1234 | 1234.00 | 1.23e+3

The last case is probably not desirable, but shouldn't happen if value < 999.5.

What do you think? Should I send a PR?

**Comment by sindresorhus** [comment]
👍
