### ISSUE TITLE
UglifyJS can't parse pretty-bytes@4.0.0 without transpilation

### ISSUE THREAD

**Issue by 1pete** [sindresorhus/pretty-bytes#22]
I use `webpack` + `babel-loader`, and got errors when build production code, where you use arrow functions and template literals.

With general webpack configuration, webpack users usually don't load modules from `node_modules` to `babel-loader`. I think you should avoid using those syntax. I'm happy to create a PR.

**Comment by SamVerschueren** [comment]
It's valid ES2015 code which is supported by Node.js 4+. We dropped support for older versions on purpose and aren't rolling this back because of webpack. It should be possible to use ES2015 and transpile it though.

**Comment by sindresorhus** [comment]
Many node modules are moving to target Node.js 4, meaning ES2015 syntax. If you use node modules for the browser you're going to have to transpile `node_modules` too, if you target older browsers. If you don't want to do that, just stay on the previous version.

Not ready yet, but would recommend [Babili](https://github.com/babel/babili) over Uglify when it becomes stable.
