### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by fpaterno** [sindresorhus/pretty-bytes#24]
With latest versions of pretty-bytes, i have this error :

> SyntaxError: /space/node_modules/grunt-pngquant/node_modules/pretty-bytes/index.js:2
> const UNITS = ['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
> ^^^^^
> Use of const in strict mode.

I'm using nodejs 4.5.0.
Can you fix this problem ?

**Comment by sindresorhus** [comment]
Then you're not actually using Node.js 4. That error only accounts on Node.js 0.10 and 0.12.
