### ISSUE TITLE
Wrong conversions

### ISSUE THREAD

**Issue by Doweig** [sindresorhus/pretty-bytes#25]
I got a weird bug when using this module with another module to convert bytes to human readable format:

The original number: 32212254720
This module: 32.2 GB
The other module: 30.00 GB

After some research I realized that you use a 1000 division to change units instead of 1024.
https://github.com/sindresorhus/pretty-bytes/blob/master/index.js#L19

Is there a reason behind it or it is a legit bug?

**Comment by sindresorhus** [comment]
Read the linked article in the readme.

tl;dr SI units are better for humans.

**Comment by Doweig** [comment]
Ok, makes sense.
Thank you for taking the time to answer 👍
