### ISSUE TITLE
Remove es6

### ISSUE THREAD

**Issue by BDiehr** [sindresorhus/pretty-bytes#26]
This module uses `const`, depending on someones build process, they may or may not run node modules through a transpiler - which is why most `npm` modules include a built or just write it in es5 compliant javascript outright

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/pretty-bytes/issues/22.

**Comment by BDiehr** [comment]
Well no point in arguing with you because it's your repo, but the vast majority of popular and maintained libraries are compiled down for you for a reason. This is only a ideological argument for enforcing people to target a higher version of node for their node_modules build process and only possibly serves to make the library more difficult to use without any maintenance benefits of ES6
