### ISSUE TITLE
Webpack's UglifyJS plugin throws an error

### ISSUE THREAD

**Issue by Alcotana** [sindresorhus/pretty-bytes#29]
Please, have a look:
![screenshot_7](https://cloud.githubusercontent.com/assets/1378484/22952901/e67c3062-f31f-11e6-8b27-367df1458ece.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/1378484/22952920/fd40088c-f31f-11e6-995e-29b4f79a32f5.png)
Could you fix this so that UglifyJS plugin in webpack could process your code correctly?

**Comment by sindresorhus** [comment]
This package requires ES2015 features. Uglify doesn't yet support that.

See: https://github.com/sindresorhus/ama/issues/446#issuecomment-281014491
