### ISSUE TITLE
Unexpected token: operator (>)

### ISSUE THREAD

**Issue by espiegel** [sindresorhus/pretty-bytes#30]
With webpack i'm getting the following error:

```
ERROR in app.aa267055ad0890445649.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/pretty-bytes/index.js:4,0]
```

Does this library have to use es6? Doesn't seem like its essential.

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/pretty-bytes/issues/29.

**Comment by SamVerschueren** [comment]
You can still use `3.0.1` though.

**Comment by espiegel** [comment]
@SamVerschueren thanks!
