### ISSUE TITLE
Provide a index.js5

### ISSUE THREAD

**Issue by ComLock** [sindresorhus/pretty-bytes#31]
So I love Ecmascript 2015, and the fact support for it is growing:
http://kangax.github.io/compat-table/es6/

Cool that node 4 supports it. 👍 

However there are a lot of javascript out there not running on node 4.
For example I'm working with Enonic XP https://enonic.com/ (my employer) which is using http://purplejs.io/ which runs on Java JVMs Nashhorn

And it seems Nashhorn wont support ES2015 before JDK9
http://winterbe.com/posts/2014/04/05/java8-nashorn-tutorial/

So perhaps instead of removing ES2015, or renaming index.js to index.es6, could you provide a transpiled index.js5 file?

(Side note: My babel didn't transpile Number.isFinite, perhaps I must update babel or configure it)
--

Similar issues:

Remove es6
https://github.com/sindresorhus/pretty-bytes/issues/26

UglifyJS can't parse pretty-bytes@4.0.0 without transpilation
https://github.com/sindresorhus/pretty-bytes/issues/22

**Comment by sindresorhus** [comment]
I'm not interested in doing that, sorry. See: https://github.com/sindresorhus/ama/issues/446#issuecomment-281014491

---

> (Side note: My babel didn't transpile Number.isFinite, perhaps I must update babel or configure it)

You also need `babel-polyfill`.

**Comment by h0ward** [comment]
Just exclude this module in your babel setup like:

```js
module.exports = {
  entry: './src/js/index.jsx',
  output: {
    filename: './dist/js/index.js'
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)\/(?!pretty-bytes\/).*/,
        loader: 'babel-loader',
        query: JSON.parse(readFileSync('.babelrc').toString()),
      }
    ]
  },
```
