### ISSUE TITLE
need to use arrow function and template strings? webpack uglifyjs errors with default options.

### ISSUE THREAD

**Issue by jeffvandyke** [sindresorhus/pretty-bytes#34]
My bundle size shot up after using this library, and after some digging, I discovered that UglifyJS runs into errors without more configuration, which could be solved if we weren't using advanced es6 (ES2015) features like arrow function and template strings.

replacing 4 lines with:
```
module.exports = function(num) {
	if (!Number.isFinite(num)) {
		throw new TypeError('Expected a finite number, got ' + (typeof num) + ': ' + num);
	}
```
fixes the issue and seems easy enough. My alternative is to try to figure out how to get UglifyJS to do what I want, or use a different library, and using a different library is easier for me. I just felt like saving people some time and making this library easier to consume. No need to not support older JavaScript programs for such a small library function right?

**Comment by kevva** [comment]
UglifyJS can't minify ES2015 code. You need to transpile it first using something like Babel or likewise. There's a more detailed explanation here You can find a more detailed explanation here: sindresorhus/ama#446.

If you use Webpack, check out [babel-engine-plugin](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
