### ISSUE TITLE
Document es2015 usage

### ISSUE THREAD

**Issue by hankthewhale** [sindresorhus/pretty-bytes#35]
Hey there. Just went through setting up this lib and hit es2015 issues like others have in the past. To fix it, I simply downgraded. 

I was wondering if you would be open to a PR that updates the readme to include a little blurb about that. Might help prevent more open issues related to this in the future but I can see why you might feel that having that documented isn't required.

**Comment by sindresorhus** [comment]
It's already defined in package.json which Node.js version this module targets. Not interested in anything in the readme.
