### ISSUE TITLE
Make it prettier? 26.2MB => 25MB

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/pretty-bytes#37]
```sh
node -i
> require('bytes')('25mb')
26214400
> require('bytes')(26214400)
'25MB'
> require('pretty-bytes')(26214400)
'26.2 MB'
```

I'd like `pretty-bytes` to be pretty and output `25` instead of `26.2`, maybe we can add a boolean second argument for this?

**Comment by sindresorhus** [comment]
This module uses base 10, while `bytes` uses base 2. I'm not interested in changing or adding an option for that. Base 10 is much more friendly to humans. macOS, iOS, and many other systems only use Base 10 to present sizes to humans now.

From the readme:

*Note that it uses base-10 (e.g. kilobyte).  
[Read about the difference between kilobyte and kibibyte.](https://web.archive.org/web/20150324153922/https://pacoup.com/2009/05/26/kb-kb-kib-whats-up-with-that/)*

**Comment by shubham1164** [comment]
You can use https://www.npmjs.com/package/filesize

**Comment by ahuglajbclajep** [comment]
This is somewhat confusing because the output by `ls -lh` is divided by 1024.
