### ISSUE TITLE
Locale-aware decimal seperator

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/pretty-bytes#4]
As you may or may not know, [24%](https://en.wikipedia.org/wiki/Decimal_mark#Hindu.E2.80.93Arabic_numeral_system) of the world uses `,` as the decimal separator, and I'd like to see an option to make pretty-bytes locale-aware.

[Number.protype.toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) isn't locale-aware and always outputs a `.` seperator. A possible replacement could be [Number.prototype.toLocaleString](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString):

``` js
num.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
```

This API is pretty recent and doesn't work on node yet, so for I guess another solution is needed.

**Comment by silverwind** [comment]
I'll wait on node 0.12 (and a bit after that) with this change, so I can use `Number.prototype.toLocaleString`. Browser support on it is decent already.

**Comment by sindresorhus** [comment]
:+1:

**Comment by mk-pmb** [comment]
If it's gonna be an option, please swap the arguments if they are (object, number). That way I could `.bind()` my fav options so I get a curried function with my prefs.

**Comment by silverwind** [comment]
@mk-pmb we decided to not do an option for it, so no worries.

**Comment by silverwind** [comment]
This actually depends on node being built with [`full-icu`](https://github.com/nodejs/node#build-with-full-icu-support-all-locales-supported-by-icu) support. It'll eventually happen for release builds (maybe in node 5.0) but until such a release is in farspread use, we can't really depend on locale-aware `Number` functions in node.

Closing for now because of that.

**Comment by meisterlampe** [comment]
What is the current status of node regarding `full-icu` support? Could this be reopened?
I know a simple API is best, but could it be possible to pass the desired language as an option? (I switch the used locale during runtime of my angular2 application and could not find a way to change the language used by browser)

**Comment by silverwind** [comment]
I'm using a pretty simple method to get the locale separator:

````js
(1.2).toLocaleString().substring(1, 2)
````

AFAIK, this should work pretty much anywhere, but I only tested in on a german locale.

**Comment by mk-pmb** [comment]
Shorter and theoretically more robust: `(0).toFixed(1).slice(1, -1)`

**Comment by silverwind** [comment]
Well for this module, we don't even need to extract the separator, we can just run `.toLocaleString` on the Number:

> ECMAScript Internationalization added the locales argument to the Number.toLocaleString() method. If the argument is undefined, this method returns localized digits specified by the OS.

I think the default should be a localized string, but I would still add an option to turn that off in case someone wants a consistently parseable output.

**Comment by meisterlampe** [comment]
Cool, thanks for reopening.
I also use .toLocalString (with the locale as parameter) for other numbers in my app. Till now that has worked like a charm.

**Comment by silverwind** [comment]
@meisterlampe would you mind sending a PR? If @sindresorhus's opinion above still stands, we can do without an option, though't I'd personally lean to still having one so a user can force a english locale to have consistently parseable output.

**Comment by sindresorhus** [comment]
@silverwind I agree. There should be an option for it.

Does `.toLocaleString` work reliably in Node.js, even without `full-icu`?

**Comment by silverwind** [comment]
> Does .toLocaleString work reliably in Node.js, even without full-icu?

I'll have to test, but I'm pretty sure the answer is no, without `full-icu`, you'll only get the english locale. This change would basically only benefit browsers.

**Comment by silverwind** [comment]
Some testing done on two machines, one using node from homebrew, one from Arch AUR. What's interesting is that this worked on both (which certainly do not have a `full-icu` build node):

````js
> (1.2).toLocaleString("de")
'1,2'
````

I was unaware about it, but apparently node can now [link against](https://github.com/nodejs/node/blob/59e48329d00cd91f6836cd91bcb8aca92acac1f6/configure#L1195) a system ICU library, and that seems to be the case on both my machines:

````js
process.config.variables.icu_gyp_path
'tools/icu/icu-system.gyp'
````

So this means support for non-english languages in node is a lot better than I thought.
