### ISSUE TITLE
function as => retrive error in IE 

### ISSUE THREAD

**Issue by ceoaliongroo** [sindresorhus/pretty-bytes#40]
I use `angular-cli 1.5.6` and i did the imports of ES6 the polyfills for Internet Explorer.

`
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-import 
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
`
But, i still get the IE Error:
`SCRIPT1002 syntax error`. in IE 11.

The error  is related to the arrow symbol, i change the code `num =>` for `function(num)` and works fine.

What polyfill i missed?
May be is necessary keep compatibility with ES5?

What do you recommend?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
