### ISSUE TITLE
Byte units are not translated

### ISSUE THREAD

**Issue by bbenoist** [sindresorhus/pretty-bytes#56]
In France, [we don't say `bytes` but `octets`](https://www.wordreference.com/enfr/byte). Thus, we don't use the `B` short name as in `42 MB`  but `o` as in `42 Mo`.

As pretty-bytes already have a `locale` option, it can be seen as a defect since the resulting string is partially localized (only the floating point is being localized).

## Example

English | Expected FR | Actual FR
--- | --- | ---
`32.5 B` | `32,5 o` | `32,5 B`
`12.3 kB` | `12,3 ko` | `12,3 kB`

**Comment by sindresorhus** [comment]
Sorry, I don't have any intentions of localizing this part as it cannot be provided by the built-in APIs. I only accepted the `locale` option as it was an easy addition.

For example:

```js
console.log(new Intl.NumberFormat('en', { notation: "compact" , compactDisplay: "long", style: 'unit', unit: 'megabyte' }).format(1)); 
```

Doesn't support all the needed units: https://tc39.es/proposal-unified-intl-numberformat/section6/locales-currencies-tz_proposed_out.html#sec-issanctionedsimpleunitidentifier

**Comment by sneko** [comment]
I'm in the same situation 👍 

@bbenoist did you find a workaround? Or did you switch to another library?

Thank you,
