### ISSUE TITLE
New option for precision

### ISSUE THREAD

**Issue by binarykitchen** [sindresorhus/pretty-bytes#57]
Would be good to have an option to allow one digit after the floating-point. 

Especially for scientific based apps.

**Comment by sindresorhus** [comment]
Can you provide an example of input, the output you currently get, and the output you'd like to get?

**Comment by binarykitchen** [comment]
What I currently get:

```js
prettyBytes(183715);
//=> '184 kB'
```

What I'm after:

```js
prettyBytes(183715, { digits: 1 });
//=> '183.7 kB'
```

**Comment by sindresorhus** [comment]
`prettyBytes(1337)` results in `1.34 kB`, so with the current behavior, I'm honestly not sure how it decides when to round or not...

How about a option, that by default, does the human readable thing and rounds when it makes sense? Like the current behavior was intended to do. And if you turn it off, you get the behavior you want with fraction digits. Like: https://developer.apple.com/documentation/foundation/bytecountformatter/1417887-isadaptive

**Comment by binarykitchen** [comment]
I hear you. Probably sounds right.

The thing is, we are porting old code to a newer system (migrations) and have to ensure behaviour stays the same. And there is always one fraction digit in our bytes, can't question this. Hence, as long as I can force that with a new option, then I'm happy with it.

**Comment by sindresorhus** [comment]
How I'm imagining it, turning off the `isAdaptive` option would result in all units having one fractional digit.
