### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by ricky11** [sindresorhus/pretty-bytes#59]
IE 11 throws an error when i package this with webpack and vue.

Error : SCRIPT1002 : SYNTAX ERROR
Chunk-vendors.js

When i dive in to chunk vendors, the line that gets highlighted is 

'eval("\n\nconst BYTE_UNITS = [\n\t'B',\n\t'kB',\n\t'MB',\n\t'GB',\n\t'TB',\n\t'PB',\n\t'EB',\n\t'ZB',\n\t'YB'\n];\n\nconst BIT_UNITS = [\n\t'b',\n\t'kbit',\n\t'Mbit',\n\t'Gbit',\n\t'Tbit',\n\t'Pbit',\n\t'Ebit',\n\t'Zbit',\n\t'Ybit'\n];\n\n/*\nFormats the given number using `Number#toLocaleString`.\n- If locale is a string, the value is expected to be a locale-key (for example: `de`).\n- If locale is true, the system default locale is used for '

Do i need to run this through babel ? What are the polyfills needed so i can include them in my transpileDependices.

Thanks.

**Comment by sindresorhus** [comment]
Webpack support questions are better asked elsewhere. I have no intention of supporting IE. It's up to you to figure out what and how to transport for IE.

**Comment by ricky11** [comment]
If any other users see this, this is how i solved it :
In vue.config.js you would just add

transpileDependencies: ['pretty-bytes']

I  wasn't sure if pretty bytes was written with es5 support or explicitly listed the polyfills i needed, know the answer now. Thanks for your support and open source projects.
