### ISSUE TITLE
Provide an option to use IEC system

### ISSUE THREAD

**Issue by pgilad** [sindresorhus/pretty-bytes#7]
would you be willing to accept a PR for that?

**Comment by MartinMuzatko** [comment]
We feed in the information from the npm package `systeminformation` Which uses `df` which uses base 2 - 1024.

It would be nice to have this configurable, because the rest of the pretty-bytes package is working wonderfully.

But eh, it is your package. So you decide.

**Comment by lmcarreiro** [comment]
> No. It's intentionally option-less. I feel base-10 is the right way to display sizes for humans.

Have you thought about adding the option to show base 2, but with the right units that nobody uses? kiB, MiB, GiB, ...

This would help people to understand that 1 kB is actually 1000 B and not 1024 B
