### ISSUE TITLE
Module parse failed: Unexpected token (74:2)

### ISSUE THREAD

**Issue by lulongwen** [sindresorhus/pretty-bytes#75]
react, dva project，npm run start will be Error

./node_modules/pretty-bytes/index.js
Module parse failed: Unexpected token (74:2)
You may need an appropriate loader to handle this file type.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/13853193/188044618-6b3ca38d-35d1-4147-9d78-cd91ea052ac1.png">

**Comment by lulongwen** [comment]
fixed:
webpackrc.js add config
extraBabelIncludes: ['node_modules/pretty-bytes']

Reason：
node_modules/pretty-bytes has ES6 code and cannot be unknown

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
