### ISSUE TITLE
Invalid configuration reported

### ISSUE THREAD

**Issue by pke** [sindresorhus/pretty-bytes#76]
I am getting this error when bundling my app

``` 
Package pretty-bytes has been ignored because it contains invalid configuration. 
Reason: Package subpath './package.json' is not defined by "exports" in /.../app/node_modules/pretty-bytes/package.json
```

Not sure if its related to this library or my project setup?

**Comment by sindresorhus** [comment]
This is a problem with your bundler. It should not depends on package.json being exported.
