### ISSUE TITLE
pretty-bytes is converting what apple shows as 1mb to 1.05mb in code

### ISSUE THREAD

**Issue by omaracrystal** [sindresorhus/pretty-bytes#78]
On macOS Montery version 12.6.1, when I go to upload a 1mb file - it shows on mac as 1mb, however, when uploading the file and converting it with prettyBytes it shows as 1.05mb because we are using the [File.prototype.size](https://developer.mozilla.org/en-US/docs/Web/API/Blob/size) to convert the file size to bytes. Why are they different?. Does apple round down or something? Also, when using the prettyBytes to convert the max file size, which we have as 1000000 bytes - it correctly shows up with the conversion with prettyBytes as 1mb. 

<img width="692" alt="Screen Shot 2022-12-16 at 3 40 51 PM" src="https://user-images.githubusercontent.com/11908147/208201096-4613e9e2-3236-4bd3-a863-114cea7d117e.png">
<img width="839" alt="Screen Shot 2022-12-16 at 3 58 35 PM" src="https://user-images.githubusercontent.com/11908147/208202341-c335bb8d-3530-4e82-b950-1125be9dbb7b.png">
<img width="505" alt="Screen Shot 2022-12-16 at 3 41 17 PM" src="https://user-images.githubusercontent.com/11908147/208201102-acb4b537-35d4-480e-8e05-130a09bee360.png">
<img width="853" alt="Screen Shot 2022-12-16 at 3 48 57 PM" src="https://user-images.githubusercontent.com/11908147/208201477-c6104228-87cf-481a-9411-d9ce79730b78.png">

File = 
[1.txt](https://github.com/sindresorhus/pretty-bytes/files/10249856/1.txt)

**Comment by sindresorhus** [comment]
I cannot answer how Apple does its rounding, but the result of `pretty-bytes` is correct.
