### ISSUE TITLE
Add support for non ES format

### ISSUE THREAD

**Issue by yhojann-cl** [sindresorhus/pretty-bytes#83]
When use a native nodejs installed from native apt repositories on Ubuntu Server or native rpm package from Redhat server, the project says:

```
$ cat index.js
const prettyBytes = require('pretty-bytes');

$ npm start

> foo@1.0.0 start
> node index.js

.../index.js:1
const prettyBytes = require('pretty-bytes');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/pretty-bytes/index.js from .../index.js not supported.
Instead change the require of index.js in ....js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (.../index.js:1:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.19.1
```

Please, add support for non ES modules.

Remember that although NodeJS has adopted the use of ES6 modules, this is not a mandatory requirement, NodeJS has managed to maintain backward compatibility, in older projects you can install babel but it is a huge and heavy package.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
